### ISSUE TITLE
Website: Website Development

### ISSUE THREAD

**Issue by andreaa0819** [easyspeakllc/easy-speak-app#28]
**Develop the website using the chosen technologies and frameworks.**
Tasks:
- [ ] Code the website's frontend and backend.
- [ ] Change theming colors and make it consistent
- [ ] Implement interactivity and forms for feedback and sign-ups.

**Comment by a1dric5** [comment]
Please reference my website design for implementation: [https://www.figma.com/file/Kustasf5w8JaXCdHVjGMV5/EasySpeak-Project-v.2?type=design&node-id=1%3A2&mode=design&t=ux7jLpHwumvQB8dX-1]
